apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: client-gateway
  name: client-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-gateway
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: client-gateway
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-nats-nest/images-register-docker/client-gateway-prod
        name: client-gateway-prod
        env: 
          - name: PORT
            value: '3000'
          - name: NATS_SERVERS
            value: nats://nats-server
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
status: {}
