apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-ms
    spec:
      containers:
      - image: southamerica-east1-docker.pkg.dev/microservices-nats-nest/images-register-docker/orders-ms-prod
        name: orders-ms-prod
        env: 
          - name: PORT
            value: '3000'
          - name: NATS_SERVERS
            value: nats://nats-server
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef: 
                name: orders-ms-secrets
                key: DATABASE_URL
        resources: {}
status: {}
