apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payments-webhook
  name: payments-webhook
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: payment-ms # este apartado del service.yml indica que app es la que va a exponer por el puerto que se configuro
                    # y el nombre no es la carpeta, es el nombre que tiene asignado el label/nombre del archivo deployment.yml
  type: NodePort
status:
  loadBalancer: {}
